<?php
$this->headTitle('Add product');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Add product'=>$this->url('add', ['action'=>'add'])
            ]);

$form = $this->form;
$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product name'
    ]);
$form->get('brand')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product brand'
    ]);
$form->get('status')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter "1" for the status "new"'
]);
$form->get('color')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product color'
]);
$form->get('size')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product size'
]);
$form->get('price')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product price'
]);
$form->get('count')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product count'
]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Add New Product</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('brand')); ?>
            <?= $this->formElement($form->get('brand')); ?>
            <?= $this->formElementErrors($form->get('brand')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('color')); ?>
            <?= $this->formElement($form->get('color')); ?>
            <?= $this->formElementErrors($form->get('color')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('size')); ?>
            <?= $this->formElement($form->get('size')); ?>
            <?= $this->formElementErrors($form->get('size')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('price')); ?>
            <?= $this->formElement($form->get('price')); ?>
            <?= $this->formElementErrors($form->get('price')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('count')); ?>
            <?= $this->formElement($form->get('count')); ?>
            <?= $this->formElementErrors($form->get('count')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('file')); ?>
            <?= $this->formElement($form->get('file')); ?>
            <?= $this->formElementErrors($form->get('file')); ?>
            <div class="hint">(PNG and JPG formats are allowed)</div>
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   