<?php
$this->headTitle('Add product');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Add product'=>$this->url('add', ['action'=>'add'])
]);

$form = $this->form;
$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product name'
]);
$form->get('brand')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product brand'
]);
$form->get('status')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product status'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Add New Product</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('brand')); ?>
            <?= $this->formElement($form->get('brand')); ?>
            <?= $this->formElementErrors($form->get('brand')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>


        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>