<?php
$this->headTitle('Update Product Info');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Add product'=>$this->url('add', ['action'=>'add'])
]);

$form = $this->form;
$form->get('color')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product color'
]);
$form->get('size')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product size'
]);
$form->get('price')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product price'
]);
$form->get('count')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product count'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Add New Product</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('color')); ?>
            <?= $this->formElement($form->get('color')); ?>
            <?= $this->formElementErrors($form->get('color')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('size')); ?>
            <?= $this->formElement($form->get('size')); ?>
            <?= $this->formElementErrors($form->get('size')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('price')); ?>
            <?= $this->formElement($form->get('price')); ?>
            <?= $this->formElementErrors($form->get('price')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('count')); ?>
            <?= $this->formElement($form->get('count')); ?>
            <?= $this->formElementErrors($form->get('count')); ?>
        </div>


        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>