<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Like a Boss')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        Like a Boss
                    </a>
                </div>
                <?php
                echo $this->mainMenu()->render();
                ?>
            </div>

        </nav>
        <div class="col-md-12">
            <!-- Breadcrumbs -->
            <?= $this->pageBreadcrumbs()->render(); ?>
        </div>
        <div class="container main-content">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> by Like a Boss </p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
