<div class="container">
    <div class="row">
        <h3 class="col-sm-offset-3 col-sm-6">Signup</h3>
    </div
    <div class="row">
        <div class="col-sm-offset-1 col-sm-2">

        </div>
        <div class="col-sm-6">
            <form action="r" method="post" accept-charset="utf-8" class="form" role="form">
                <div class="row">
                    <div class="col-xs-6 col-md-6">
                        <input type="text" name="firstname" value="" class="form-control input-lg" placeholder="First Name"  />                        </div>
                    <div class="col-xs-6 col-md-6">
                        <input type="text" name="lastname" value="" class="form-control input-lg" placeholder="Last Name"  />                        </div>
                </div>
                <input type="text" name="email" value="" class="form-control input-lg" placeholder="Your Email"  /><input type="password" name="password" value="" class="form-control input-lg" placeholder="Password"  /><input type="password" name="confirm_password" value="" class="form-control input-lg" placeholder="Confirm Password"  />
                <label>Birth Date</label>
                <label>Gender : </label>
                <label class="radio-inline">
                    <input type="radio" name="gender" value="M" id=male />Male
                </label>
                <label class="radio-inline">
                    <input type="radio" name="gender" value="F" id=female />Female
                </label>
                <br />
                <span class="help-block">By clicking Create my account, you agree to our Terms and that you have read our Data Use Policy, including our Cookie Use.</span>
                <button class="btn btn-lg btn-primary btn-block signup-btn" type="submit">Create my account</button>
            </form>
        </div>
    </div>
</div>
</div>